package com.jesushz.spendless.core.presentation.designsystem.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF5A00C8)
val OnPrimary = Color(0xFFFFFFFF)
val Secondary = Color(0xFF5F6200)
val TertiaryContainer = Color(0xFFC4E0F9)
val PrimaryContainer = Color(0xFF8138FF)
val SecondaryContainer = Color(0xFFD2E750)
val OnSecondaryContainer = Color(0xFF414300)
val Error = Color(0xFFA40019)
val OnError = Color(0xFFFFFFFF)
val Success = Color(0xFF29AC08)
val Background = Color(0xFFFEF7FF)
val OnBackground = Color(0xFF1D1A25)
val Surface = Color(0xFFFCF9F9)
val OnSurface = Color(0xFF1B1B1C)
val SecondaryFixed = Color(0xFFE5EA58)
val SecondaryFixedDim = Color(0xFFC9CE3E)
val SurfaceContainerLowest = Color(0xFFC9CE3E)
val SurfaceContainerLow = Color(0xFFF6F3F3)
val SurfaceContainer = Color(0xFFF0EDED)
val SurfaceContainerHighest = Color(0xFFE4E2E2)
val OnSurfaceVariant = Color(0xFF44474B)
val Outline = Color(0xFF75777B)
val InverseSurface = Color(0xFF303031)
val InverseOnSurface = Color(0xFFF3F0F0)
val PrimaryFixed = Color(0xFFEADDFF)
val InversePrimary = Color(0xFFD2BCFF)